### ISSUE TITLE
Missing .cfg files even though .png files are there

### ISSUE THREAD

**Issue by ckeech** [thebezelproject/bezelproject-MasterSystem#1]
Love this script/project. Thanks so much 👍 

I have noticed that some games are missing their .cfg file, even though they have a bezel image file. For example:

I have these:
overlays\GameBezels\MasterSystem\Alex Kidd in Miracle World (USA, Europe).cfg"
overlays\GameBezels\MasterSystem\Alex Kidd in Miracle World (USA, Europe).png"
overlays\GameBezels\MasterSystem\Alex Kidd in Miracle World (USA, Europe) (v1.1).png"

So it's missing:
overlays\GameBezels\MasterSystem\Alex Kidd in Miracle World (USA, Europe) (v1.1).cfg"

Is this just because it's a work in progress, or am I missing something? When I look up the no intro set I see 
Alex Kidd in Miracle World (USA, Europe) (v1.1) is there and 
Alex Kidd in Miracle World (USA, Europe)  isn't so I would have thought this issue would be the other way around.

Thanks.

**Comment by thebezelproject** [comment]
Added missing cfg files.
