### ISSUE TITLE
shinobi png missing

### ISSUE THREAD

**Issue by BanditTech** [thebezelproject/bezelproject-MasterSystem#2]
the PNG for the shinobi bezel is missing, the files that point to the bezel are present though.

**Comment by BanditTech** [comment]
![shinobi usa europe](https://user-images.githubusercontent.com/13251996/52761360-f3652400-2fc7-11e9-909a-0aa36230e041.png)
just a quickie

**Comment by thebezelproject** [comment]
Added png file.
