### ISSUE TITLE
TV Mask

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-MasterSystem#4]
I miss the TV mask. It would be perfect following the format of other systems such as NES, SNES, MEGADRIVE ...

Could you generate them with adding this mask?

![tv](https://user-images.githubusercontent.com/20826760/74691482-4416ea80-51e3-11ea-8596-657b5459ca47.png)

**Comment by thebezelproject** [comment]
We have no plans to add the mask ourselves (there was a vote on what style to use). You are free to add it yourself, and we have had a number of members do this for their personal collection.
