### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-MasterSystem#5]
Some overlays contain transparent / translucent pixels outside the desired area.

Here the list:

Alex Kidd in Shinobi World (USA, Europe).png
Alien Storm (Europe).png
Ariel - The Little Mermaid (Brazil).png
Asterix (Europe) (En,Fr) (Rev 1).png
Dinobasher Starring Bignose the Caveman (Europe) (Proto).png
Dynamite Dux (Europe).png
Fantasy Zone - The Maze (USA, Europe).png
R.C. Grand Prix (USA, Europe).png
Rainbow Islands - Story of the Bubble Bobble 2 (Europe).png
Rambo - First Blood Part II (USA).png
Rambo III (USA, Europe).png
Rampart (Europe).png
Strider II (Europe).png
Super Off Road (Europe).png
Vigilante (USA, Europe).png
Wanted (USA, Europe).png
Wonder Boy III - The Dragon's Trap (USA, Europe).png
WWF Wrestlemania - Steel Cage Challenge (Europe).png
Zaxxon 3-D (World).png

Here you can see the specific areas that have pixels outside the desired area.

https://drive.google.com/file/d/1PhEvkBrXT88a727xTEnekYXcOXLVYGXM/view?usp=sharing

**Comment by thebezelproject** [comment]
Thanks! I have updated the files.
